--linea de prueb
BEGIN
      create or replace table `.dev_curate.dim_tramo` AS
      SELECT CONCAT(SUBSTR(Tramo,1,3),'<>',SUBSTR(Tramo,4,6)) pk_tramo, 
            Tramo AS TRAMO,
            SUBSTR(Tramo,1,3) FROM_ARIPORT,
            SUBSTR(Tramo,4,6) TO_ARIPORT,
            Round_Trip AS RUTA,
            Mercado AS MERCADO,
            Negocio AS NEGOCIO,
            Millas AS DISTACIAENMILLAS,
      FROM `.dev_raw.segmentacion`;
END