BEGIN

DECLARE Year_min INT64 DEFAULT (SELECT MIN(EXTRACT(YEAR FROM Fecha)) FROM `.fuentes.presupuesto`);
CREATE OR REPLACE TABLE `.dev_curate.presupuesto_yield_mensual` AS
WITH a AS (
SELECT 
      y.Ruta Ruta,
      EXTRACT(MONTH FROM y.departure_date) Mes,
      EXTRACT(YEAR FROM y.departure_date) as YEAR,
      y.tipo_vuelo Tipovuelo_real,
      SUM(y.air+y.ancilliary) Ingresos_real,
      SUM(y.RP) Pax_real,
      SUM(y.capacidad) Capacidad_real,
      p.Tipovuelo,
      p.ingresos Ingresos_pres,
      p.pax Pax_pres,
      p.sillas Capacidad_pres,
      COUNT(*) Frecuencia_mensual,
      case when (SUM(p.ingresos) is null and SUM(p.pax) is null and SUM(p.sillas) is null) then 3
      when (SUM(y.air) is null and SUM(y.bkd) is null and SUM(y.capacidad) is null) or (sum(y.air)=0) then 2
      else 1
      end as clasificacion
FROM `.dev_raw.yield_ingresos` y
LEFT JOIN `.fuentes.presupuesto` p ON y.ruta=p.ruta AND EXTRACT(MONTH FROM y.departure_date)=p.Mes and EXTRACT(YEAR FROM y.departure_date)=extract(YEAR FROM p.Fecha) and y.tipo_vuelo=if(p.Tipovuelo='Charter','CHARTER','COMMERCIAL')
GROUP BY Mes,y.Ruta,p.Ruta,y.tipo_vuelo,YEAR,p.Tipovuelo,p.ingresos,p.pax,p.sillas

UNION ALL

SELECT p.Ruta,
      p.Mes,
      extract(YEAR FROM p.Fecha),
      null Tipovuelo_real,
      null Ingresos_real,
      null Pax_real,
      null Capacidad_real,
      p.Tipovuelo,
      p.ingresos Ingresos_pres,
      p.pax Pax_pres,
      p.sillas Capacidad_pres,
      null Frecuencia_mensual,
      2 clasificacion
FROM `.fuentes.presupuesto` p
WHERE CONCAT(p.Ruta,if(p.Tipovuelo='Charter','CHARTER','COMMERCIAL'),p.Mes,extract(YEAR FROM p.Fecha)) NOT IN (SELECT CONCAT(Ruta,tipo_vuelo,EXTRACT(MONTH FROM departure_date),EXTRACT(YEAR FROM departure_date)) FROM `.dev_raw.yield_ingresos`))

SELECT * FROM a;
END